# Generated by Django 4.0.4 on 2022-05-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_ticktes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ticktes',
            new_name='tickets',
        ),
    ]
